# Generated by Django 5.1.15 on 2026-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='software_interest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
